app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('degree/',degree,name='degree'),
    path('mca/',mca,name='mca'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('ssc/',ssc,name='ssc'),
    path('inter/',inter,name='inter'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def degree(request):
    return render(request,'degree.html')



def mca(request):
    return render(request,'mca.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def ssc(request):
    return render(request,'ssc.html')


def inter(request):
    return render(request,'inter.html')

templates/degree.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>degree</h1>
        <h1>I completed my B.Sc computers in the year of 2020 </h1>
        <a href="{% url 'app1:mca' %}">go to mca</a><br>
        <a href="{% url 'app2:ssc' %}">go to ssc</a><br>
        <a href="{% url 'app2:inter' %}">go to inter</a>
    </center>
</body>
</html>

templates/inter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>inter</h1>
        <h1>I completed my intermediate in the year of 2017</h1>
        <a href="{% url 'app1:degree' %}">go to degree</a><br>
        <a href="{% url 'app1:mca' %}">go to mca</a><br>
        <a href="{% url 'app2:ssc' %}">go to ssc</a>
    </center>
</body>
</html>

templates/mca.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>MCA</h1>
        <h1>I completed my MCA computers in the year of 2022</h1>
        <a href="{% url 'app1:degree' %}">go to degree</a><br>
        <a href="{% url 'app2:ssc' %}">go to ssc</a><br>
        <a href="{% url 'app2:inter' %}">go to inter</a>
    </center>
</body>
</html>

templates/ssc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>ssc</h1>
        <h1>I completed my ssc in the year of 2015 </h1>
        <a href="{% url 'app1:degree' %}">go to degree</a><br>
        <a href="{% url 'app1:mca' %}">go to mca</a><br>
        <a href="{% url 'app2:inter' %}">go to inter</a>
    </center>
</body>
</html>